version: '3.7'

services:
  blog:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    image: mushroom3/django-blog-dev:${DOCKER_TAG:-latest}
    volumes:
      - ./web/:/usr/src/web/
      - redis_socket:/redis_socket
      - postgres_socket:/postgres_socket
    ports:
      - 8008:8000
    env_file:
      - docker/dev/env/.env
      - docker/dev/env/.db.env
      - docker/prod/env/.data.env
      - docker/prod/env/.email.env
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - microservice_network
      - separated_network
    extra_hosts:
      - "DOCKER-GATEWAY-HOST:172.17.0.1"  # Linux OS get access from docker container to localhost
      # host.docker.internal - For docker in Windows. No other action is required.
      # If You need to connect to PostgreSql in localhost, just use host.docker.internal instead of localhost
    healthcheck:
      test: curl --fail -s http://localhost:8000$$HEALTH_CHECK_URL || exit 1
      interval: 1m30s
      timeout: 3s
      retries: 3
  db:
    build:
      context: .
      dockerfile: docker/dev/db/Dockerfile
    image: mushroom3/django-blog-db-dev:${DOCKER_TAG:-latest}
    hostname: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_socket:/postgres_socket
    ports:
      - "5432:5432"
    env_file:
      - docker/dev/env/.db.env
    networks:
      - separated_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 50s
      timeout: 5s
      retries: 5
  redis:
    build:
      context: .
      dockerfile: ./docker/dev/redis/Dockerfile
    image: mushroom3/django-blog-redis:${DOCKER_TAG:-latest}
    restart: always
    volumes:
      - redis_data:/data
      - redis_socket:/redis_socket
    networks:
      - separated_network
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 1m20s
      timeout: 5s
      retries: 3
  celery:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    image: mushroom3/django-blog:${DOCKER_TAG:-latest}
    entrypoint: ""
    command: celery -A src worker -l info
    volumes:
      - ./web/:/usr/src/web/
      - redis_socket:/redis_socket
      - postgres_socket:/postgres_socket
    env_file:
      - docker/dev/env/.env
      - docker/dev/env/.db.env
      - docker/prod/env/.data.env
      - docker/dev/env/.email.env
    depends_on:
      - redis
    restart: always
    networks:
      - separated_network
    extra_hosts:
      - "docker-gateway-host:172.17.0.1"


volumes:
  postgres_data:
  redis_data:
  redis_socket:
  postgres_socket:

networks:
  microservice_network:
    driver: bridge
    name: local_microservice_network
  separated_network:
    driver: bridge
