apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blogchart.fullname" . }}
  labels:
    {{- include "blogchart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "blogchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "blogchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "blogchart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: blogchart-secrets
                  key: superUserEmail
                  optional: false
            - name: SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blogchart-secrets
                  key: superUserPassword
                  optional: false
            - name: ENABLE_RENDERING
              value: {{ .Values.django.enableRendering | quote }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: blogchart-secrets
                  key: secretKey
                  optional: false
            - name: DJANGO_ALLOWED_HOSTS
              value: {{ required "django allowed hosts is required" .Values.django.allowedHosts | quote }}
            - name: POSTGRES_HOST
              value: {{ default (printf "%s-postgresql" .Release.Name) .Values.postgresql.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.django.db.postgresPort | quote }}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: blogchart-secrets
                  key: postgresqlDatabase
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: blogchart-secrets
                  key: username
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blogchart-secrets
                  key: postgresqlPassword
                  optional: false
            - name: REDIS_HOST
              value: {{ default (printf "%s-redis-master" .Release.Name) .Values.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.django.redis.redisPort | quote }}
            - name: REDIS_URL
              value: "redis://$(REDIS_HOST):$(REDIS_PORT)"
            - name: REDIS_DB
              value: {{ .Values.django.redis.redisDB | quote }}
            - name: DEBUG
              value: {{ .Values.django.debug | quote }}
            - name: SITE_ID
              value: {{ .Values.django.siteId | quote }}
            - name: SQL_ENGINE
              value: {{ .Values.django.sqlEngine | quote }}
            - name: BACKEND_SITE
              value: {{ .Values.django.backendSite| quote }}
            - name: ADMIN_URL
              value: {{ .Values.django.adminUrl | quote }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.django.djangoSettingsModule | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
