apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.flower.flowerFullName }}
  labels:
    {{- include "blogchart.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.flower.flowerFullName | quote }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "blogchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "blogchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "blogchart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.celeryContainerName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.flower.flowerImage }}:{{ .Values.flower.flowerTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.flower.pullPolicy }}
          ports:
            - name: http
              containerPort: 5555
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: FLOWER_PORT
              value: {{ .Values.flower.flowerPort | quote }}
            - name: REDIS_HOST
              value: {{ default (printf "%s-redis-master" .Release.Name) .Values.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.django.redis.redisPort | quote }}
            - name: CELERY_BROKER_URL
              value: "redis://$(REDIS_HOST):$(REDIS_PORT)/3"

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
