apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "blogchart.fullname" . }}
  labels:
    {{- include "blogchart.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "blogchart.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "blogchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "blogchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "blogchart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
            httpGet:
              path: {{ .Values.django.healthCheckUrl }}
              port: http
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
            httpGet:
              path: {{ .Values.django.healthCheckUrl }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: blogchart-secrets
                  key: superUserEmail
                  optional: false
            - name: SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blogchart-secrets
                  key: superUserPassword
                  optional: false
            - name: ENABLE_RENDERING
              value: {{ .Values.django.enableRendering | quote }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: blogchart-secrets
                  key: secretKey
                  optional: false
            - name: DJANGO_ALLOWED_HOSTS
              value: {{ required "django allowed hosts is required" .Values.django.allowedHosts | quote }}
            - name: POSTGRES_HOST
              value: {{ default (printf "%s-postgresql" .Release.Name) .Values.postgresql.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.django.db.postgresPort | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database  | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PORT
              value: {{ .Values.django.redis.redisPort | quote }}
            - name: REDIS_URL
              value: "redis://$(REDIS_HOST):$(REDIS_PORT)"
            - name: REDIS_DB
              value: {{ .Values.django.redis.redisDB | quote }}
            - name: CELERY_BROKER_URL
              value: "$(REDIS_URL)/3"
            - name: CELERY_RESULT_BACKEND
              value: "$(REDIS_URL)/3"
            - name: DEBUG
              value: {{ .Values.django.debug | quote }}
            - name: SITE_ID
              value: {{ .Values.django.siteId | quote }}
            - name: SQL_ENGINE
              value: {{ .Values.django.sqlEngine | quote }}
            - name: BACKEND_SITE
              value: {{ .Values.django.backendSite| quote }}
            - name: ADMIN_URL
              value: {{ .Values.django.adminUrl | quote }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.django.djangoSettingsModule | quote }}
          volumeMounts:
            - name: {{ (printf "%s-media-storage" .Release.Name) }}
              mountPath: /web/media
        - name: {{ .Values.celeryContainerName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
          {{- range .Values.celery.args}}
            - {{ . | toYaml | indent 4 | trim }}
          {{- end }}
          command:
            - ""
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: blogchart-secrets
                  key: secretKey
                  optional: false
            - name: POSTGRES_HOST
              value: {{ default (printf "%s-postgresql" .Release.Name) .Values.postgresql.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.django.db.postgresPort | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database  | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PORT
              value: {{ .Values.django.redis.redisPort | quote }}
            - name: REDIS_URL
              value: "redis://$(REDIS_HOST):$(REDIS_PORT)"
            - name: REDIS_DB
              value: {{ .Values.django.redis.redisDB | quote }}
            - name: CELERY_BROKER_URL
              value: "$(REDIS_URL)/3"
            - name: CELERY_RESULT_BACKEND
              value: "$(REDIS_URL)/3"
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: emailHost
                  optional: false
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: emailPort
                  optional: false
            - name: EMAIL_USE_TLS
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: emailUseTLS
                  optional: false
            - name: EMAIL_USE_SSL
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: emailUseSSL
                  optional: false
            - name: DEFAULT_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: defaultFromEmail
                  optional: false
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: emailHostUser
                  optional: false
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: emailHostPassword
                  optional: false
            - name: EMAIL_BACKEND
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: emailBackend
                  optional: false

      volumes:
        - name: {{ (printf "%s-media-storage" .Release.Name) }}
          persistentVolumeClaim:
            claimName: {{ include "blogchart.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
