# Generated by Django 3.1.7 on 2021-06-23 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user_image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('user_birthdate', models.DateField()),
                ('user_bio', models.TextField(default='', help_text='Bio', max_length=2000)),
                ('user_name', models.CharField(default='', help_text='Name', max_length=200)),
                ('user_surname', models.CharField(default='', help_text='Surname', max_length=200)),
                ('user_url', models.URLField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
