# Generated by Django 3.1.7 on 2021-07-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_parentcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentComment',
        ),
    ]
