# Generated by Django 3.1.7 on 2021-07-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_parentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
    ]
