version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml #prometheus.yml present in the root dir
  grafana:
    image: grafana/grafana
    ports:
      - "3060:3060"
