name: Coverage

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Run coverage.py"
        run: |
          docker-compose build
#          docker-compose run --entrypoint="" -u root blog coverage run manage.py test
          docker-compose run --entrypoint="" -u root blog coverage xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./web/

