name: 'Terraform Deployment Dev'

on:
  workflow_dispatch:


jobs:
  deploy-service:
    name: 'Deploy Service'
    permissions:
      id-token: 'write'
      contents: 'read'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Deployment
        id: tf-dpl
        working-directory: terraform
        run: |
          terraform init
          terraform plan -out=tfplan -input=false -var-file=environments/dev.tfvars
          terraform apply -input=false tfplan
