name: Kubernetes Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/checkout@v2
      - name: Deploy
        with:
          image: dtzar/helm-kubectl:2.12.1
          command: |
            cd blogchart
            kubectl config set-cluster k8s --certificate-authority=${{ secrets.CERT }} --server=https://51.250.80.194 --kubeconfig=test.kubeconfig
            kubectl config set-credentials admin-user --token=${{ secrets.SA_TOKEN }} --kubeconfig=test.kubeconfig
            kubectl config set-context default --cluster=k8s --user=admin-user --kubeconfig=test.kubeconfig
            kubectl config use-context default --kubeconfig=test.kubeconfig
            cat test.kubeconfig
            kubectl get pods --namespace=redis --kubeconfig=test.kubeconfig
            helm --client-only init --stable-repo-url https://charts.bitnami.com/bitnami
            helm dep build .
            helm install blogchart .
