name: Kubernetes Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy
        uses: docker://dtzar/helm-kubectl:2.12.1
        with:
          args: |
            kubectl config set-cluster k8s --server=${{ secrets.K8S_API }}
            kubectl config set clusters.k8s.certificate-authority-data ${{ secrets.K8S_CA_DATA }}
            kubectl config set-credentials yc-service-account --token=${{ secrets.K8S_TOKEN }}
            kubectl config set-context default --cluster=k8s --user=yc-service-account
            kubectl config use-context default
            —Åd blogchart
            helm init --client-only --stable-repo-url https://charts.bitnami.com/bitnami
            helm dep build
            helm upgrade --install blogchart .
            kubectl get pods


