name: Kubernetes Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          cd blogchart
          docker --build-arg CERT=${{ secrets.CERT }} --build-arg SA_TOKEN=${{ secrets.$SA_TOKEN }} build . -t deploy -f Dockerfile
