name: Kubernetes Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy
        uses: docker://dtzar/helm-kubectl:3.8.1
        with:
          entrypoint: ./entrypoint.sh
