name: Kubernetes Deploy

on:
  push:
    branches: [ cicd_kubernetes ]
  workflow_dispatch:

jobs:
  deploy-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/checkout@v2
#      - name: Deploy
#        run: |
#          cd blogchart
#          docker build --build-arg CERT="${{ secrets.CERT }}" --build-arg SA_TOKEN="${{ secrets.SA_TOKEN }}" -t deploy . -f Dockerfile
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'blogchart'
          namespace: 'blog'
          chart: './blogchart'
          token: '${{ github.token }}'
          value-files: >-
          [
              "values.yaml"
          ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
